export const hotels = [
  {
    id: 1,
    name: "The Plaza Hotel",
    address: "New York City, USA Country",
    description: "A cozy hotel in the heart of the city.",
    rating: 4.5,
    price_per_night: 450,
    amenities: ["Free Wi-Fi, " , "Swimming Pool, ", "Restaurant"],
    image_url: "https://s3.scoopwhoop.com/anj/dsc/497184253.JPG",
  },
  {
    id: 2,
    name: "The Ritz-Carlton",
    address: "Paris, France Country",
    description: "Luxurious accommodations with a view.",
    rating: 4.8,
    price_per_night: 250,
    amenities: ["Free Breakfast, ", "Gym, ", "Spa"],
    image_url: "https://images.pexels.com/photos/1134176/pexels-photo-1134176.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260",
  },
  {
    id: 3,
    name: "The Four Seasons Hotel",
    address: "Bora Bora, French Polynesia Country",
    description: "Budget-friendly option for travelers.",
    rating: 3.9,
    price_per_night: 75,
    amenities: ["Free Parking, ", "Bar", "Room Service"],
    image_url: "https://lnhotels.in/uploads/banners/RCKqI1%20PARK%20N%20Facade.JPG",
  },
  {
    id: 4,
    name: "Seaside Paradise Resort",
    address: "Ocean View Drive, Beach City, Country",
    description: "Experience a tranquil getaway by the beach.",
    rating: 4.7,
    price_per_night: 300,
    amenities: ["Private Beach Access, ", "Spa, ", "Fine Dining"],
    image_url: "http://travelji.com/wp-content/uploads/Hotel-Tips.jpg",
  },
  {
    id: 5,
    name: "Mountain View Lodge",
    address: "Scenic Mountain Road, Mountain Town, Country",
    description: "Escape to the serene mountainside retreat.",
    rating: 4.6,
    price_per_night: 180,
    amenities: ["Hiking Trails, ", "Fireplace, ", "Hot Tub"],
    image_url: "https://momblogsociety.com/wp-content/uploads/2019/03/hotels.jpg",
  },
  {
    id: 6,
    name: "Urban Oasis Hotel",
    address: "Downtown Avenue, City, Country",
    description: "A modern hotel in the heart of the bustling city.",
    rating: 4.2,
    price_per_night: 200,
    amenities: ["Rooftop Bar, ", "Fitness Center, ", "Conference Rooms"],
    image_url: "http://media.architecturaldigest.com/photos/57e42deafe422b3e29b7e790/master/pass/JW_LosCabos_2015_MainExterior.jpg",
  },
  {
    id: 7,
    name: "Historic Inn & Suites",
    address: "Historic Street, Old Town, Country",
    description: "Step back in time at this charming historic inn.",
    rating: 4.4,
    price_per_night: 120,
    amenities: ["Antique Decor, ", "Courtyard Garden, ", "Complimentary Breakfast"],
    image_url: "https://images.pexels.com/photos/2034335/pexels-photo-2034335.jpeg?cs=srgb&dl=architecture-building-chairs-2034335.jpg&fm=jpg",
  },
  {
    id: 8,
    name: "Lakefront Cabin Retreat",
    address: "Lakeview Drive, Lakeside Town, Country",
    description: "Unwind in a cozy cabin with stunning lake views.",
    rating: 4.9,
    price_per_night: 220,
    amenities: ["Lake Access, ", "Fishing Dock, ", "Campfire Pit"],
    image_url: "https://www.ahstatic.com/photos/9399_ho_00_p_1024x768.jpg",
  },
  {
    id: 9,
    name: "Tropical Paradise Resort",
    address: "Palm Beach Road, Island Paradise, Country",
    description: "Escape to an island paradise with pristine beaches.",
    rating: 4.8,
    price_per_night: 350,
    amenities: ["Private Bungalows, ", "Water Sports, ", "Tiki Bar"],
    image_url: "http://bocadolobo.com/blog/wp-content/uploads/2014/09/116.jpg",
  },
  {
    id: 10,
    name: "Chateau Elegance Hotel",
    address: "Chateau Lane, Countryside, Country",
    description: "Experience luxury in a beautiful chateau setting.",
    rating: 4.7,
    price_per_night: 400,
    amenities: ["Wine Cellar, ", "Championship Golf Course, ", "Fine Dining"],
    image_url: "https://www.amazingviralnews.com/wp-content/uploads/2020/12/Hotel.jpg",
  },
  {
    id: 11,
    name: "Riverside Retreat",
    address: "Riverfront Avenue, Riverside City, Country",
    description: "Relax by the river in a serene and peaceful environment.",
    rating: 4.6,
    price_per_night: 175,
    amenities: ["River Views, ", "Picnic Area, ", "Canoe Rentals"],
    image_url: "https://2486634c787a971a3554-d983ce57e4c84901daded0f67d5a004f.ssl.cf1.rackcdn.com/florida-hotel-and-conference-center/media/FH-Gallery-1-598b45769980a.jpg",
  },
  {
    id: 12,
    name: "Alpine Lodge",
    address: "Mountain View Road, Alpine Town, Country",
    description: "Experience the beauty of the Alps in this cozy lodge.",
    rating: 4.5,
    price_per_night: 190,
    amenities: ["Ski-In/Ski-Out, ", "Sauna, ", "Mountain Biking"],
    image_url: "https://www.studentuniverse.com/blog/wp-content/uploads/2019/05/hotel-feat.jpg",
  },
  {
    id: 13,
    name: "Desert Oasis Resort",
    address: "Oasis Road, Desert City, Country",
    description: "Escape to the desert and enjoy luxurious accommodations.",
    rating: 4.6,
    price_per_night: 280,
    amenities: ["Spa & Wellness, ", "Camel Rides, ", "Desert Safari"],
    image_url: "http://images.huffingtonpost.com/2014-05-19-RitzSouthBeach-thumb.jpg",
  },
  {
    id: 14,
    name: "Rural Farm Stay",
    address: "Countryside Lane, Farmville, Country",
    description: "Experience life on a working farm and enjoy fresh produce.",
    rating: 4.3,
    price_per_night: 110,
    amenities: ["Farm Tours, ", "Farm-to-Table Dining, ", "Hiking Trails"],
    image_url: "https://media-cdn.tripadvisor.com/media/photo-s/18/c9/61/60/our-luxury-hotel.jpg",
  },
  {
    id: 15,
    name: "City View Suites",
    address: "Downtown Street, City, Country",
    description: "Enjoy city life from your comfortable suite with a view.",
    rating: 4.4,
    price_per_night: 210,
    amenities: ["City Views, ", "Fitness Center, ", "Room Service"],
    image_url: "https://cdn.galaxy.tf/unit-media/seh-unit/uploads/images/hotel_photo/001/562/762/newbrand-9303-fr-tremblay-en-france-hotel-28-compressor-wide.jpg",
  },
  {
    id: 16,
    name: "Beachfront Bungalows",
    address: "Beachfront Avenue, Seaside City, Country",
    description: "Relax in beachfront bungalows with direct beach access.",
    rating: 4.7,
    price_per_night: 320,
    amenities: ["Beachfront Views, ", "Water Sports, ", "Beach Bar"],
    image_url: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/d7/1c/2a/exterior.jpg?w=900&h=-1&s=1",
  },
  {
    id: 17,
    name: "Historic Mansion Hotel",
    address: "Mansion Lane, Historic Town, Country",
    description:
      "Step back in time at a beautifully restored historic mansion.",
    rating: 4.6,
    price_per_night: 250,
    amenities: ["Historic Tours, ", "Gardens, ", "Fine Dining"],
    image_url: "http://www.techspot.com/images2/news/bigimage/2015/11/2015-11-24-image-15.jpg",
  },
  {
    id: 18,
    name: "Lakeside Retreat",
    address: "Lakeside Drive, Lakeview City, Country",
    description:
      "Relax by the tranquil lakeside in comfortable accommodations.",
    rating: 4.5,
    price_per_night: 180,
    amenities: ["Lakeside Views, ", "Fishing, ", "Picnic Area"],
    image_url: "https://cache.marriott.com/marriottassets/marriott/GFLCY/gflcy-exterior-0008-hor-feat.jpg",
  },
  {
    id: 19,
    name: "Mediterranean Villa",
    address: "Villa Street, Mediterranean Coast, Country",
    description:
      "Experience the beauty of the Mediterranean in a luxurious villa.",
    rating: 4.8,
    price_per_night: 350,
    amenities: ["Private Beach Access, ", "Pool, ", "Mediterranean Cuisine"],
    image_url: "https://qtxasset.com/styles/breakpoint_xl_880px_w/s3fs/hotelmanagement/1516746817/limelight.dusk_.jpg?JlI3cTkbLPirT8CFCNORsi62l5WA2gTv&itok=8T2VyfoU",
  },
  {
    id: 20,
    name: "Cozy Mountain Cabin",
    address: "Mountain Cabin Lane, Mountain Retreat, Country",
    description: "Escape to the mountains in a cozy and secluded cabin.",
    rating: 4.4,
    price_per_night: 160,
    amenities: ["Mountain Views, ", "Hiking Trails, ", "Fireplace"],
    image_url: "https://i.redd.it/46j0jq100zn01.jpg",
  },
];
